# Generated by Django 4.1.7 on 2023-03-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinno', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'studentinfo',
                'verbose_name_plural': 'studentinfos',
            },
        ),
    ]
